### ISSUE TITLE
Input format?

### ISSUE THREAD

**Issue by theronic** [frankmcsherry/pagerank#11]
I can't run the example without an input file. What should the input file look like? Could you add a trivial example to the repo? Thanks!

**Comment by theronic** [comment]
Figured it out from reading `parse.rs`. my-edgelists.txt should look like this:

```
0	1
1	2
2	8
8	0
2	3
3	4
4	1
1	4
```

...where the spaces are `\t` tab characters :).

**Comment by frankmcsherry** [comment]
Glad it worked out! There are also example files linked in the README.md.
