### ISSUE TITLE
Apply updates?

### ISSUE THREAD

**Issue by florianre-zz** [frankmcsherry/pagerank#9]
Hi,

I'd like to run your algorithm multiple times with topology updates in between runs (edge deletion and addition). Is it possible with this implementation? Or is your pagerank implementation in timely dataflow more appropriate?

Thanks

**Comment by frankmcsherry** [comment]
Hi!

Good question. In principle this implementation could be lightly retooled to write our ranks at the end and read ranks back in at the beginning of its next invocation. Depending on how often you update the edges this might work fine for you (it will re-index the graph each time, but this seems to take a fraction of the computation if you plan to do multiple iterations).

The timely dataflow pagerank example is not especially well engineered, but it is arguably more appropriate for incremental updates. It attempts to do the minimal amount of work required for small updates, whereas this version does a fixed large amount of work but does it relatively efficiently. I'd guess that either:

1. You have many updates at a time, to the point that you are fine re-running the graph assembly here. In which case you would just need to tweak this code to write out and read in the ranks.
2. You have relatively few updates, or a high intended refresh rate (e.g. sub-second), in which case the timely dataflow example is more appropriate. However, this implementation could use a bunch of attention in terms of absolute performance.

**Comment by florianre-zz** [comment]
Awesome thank you!
